### ISSUE TITLE
Build fails due to solr config

### ISSUE THREAD

**Issue by yafsn** [tumblr/collins#304]
During builds of the [docker image](https://github.com/tumblr/collins/blob/master/Dockerfile), [package.sh](https://github.com/tumblr/collins/blob/master/scripts/package.sh) fails because the path to the solr config doesn't exist:

> error: cp: cannot stat ‘../conf/solr/conf/*’: No such file or directory

It looks like either the path needs to change from [solr/cores](https://github.com/tumblr/collins/tree/master/conf/solr/cores) to solr/conf or [package.sh](https://github.com/tumblr/collins/blob/master/scripts/package.sh) needs to use solr/cores as the source instead of solr/conf

> cp -R ../conf/solr/conf/* $CONF_DIR/solr/conf/

If you let me know which way it should go, I can fork it and put in a PR.

**Comment by maddalab** [comment]
@yafsn you are right. That would also be me who broke it. Looking into it right now. Thanks for the issue.

**Comment by maddalab** [comment]
@yafsn can you please also tell me what you are trying. As a heads up, the master branch has breaking changes and the docs are correct for the previous release. (The docker docs your referenced are fine for master.)

**Comment by yafsn** [comment]
@maddalab I've been running the 1.3.0 release, but wanted to try out your updates from last month.  My ldap setup requires ldaps and a bind account so it was a good time to pull from master.

**Comment by maddalab** [comment]
Awesome let me know how it goes, the documentation on the latest is sparse (at places incorrect) we are working on it. LMK if you get stuck and need help.

**Comment by maddalab** [comment]
Since we are working towards a 2.0 (major version upgrade) we have a couple of backwards incompatible changes.

Off the top of my head, update your [akka config](https://github.com/tumblr/collins/blob/master/conf/dev_base.conf#L286)

And, you will have to repopulate your [solr index](https://github.com/tumblr/collins/blob/master/conf/routes#L47)

Update the configuration for [decorators](https://github.com/tumblr/collins/blob/master/conf/dev_base.conf#L144)

This first change allows for more tuning on solr updates, the setting in the config in the repo give the same semantics as the previous hardcoded values.

The second is required due to upgrading solr dependencies.

**Comment by yafsn** [comment]
I rebuilt my image and it worked fine.  Thanks for the quick followup and the tips on the upcoming changes.
