### ISSUE TITLE
Has 10Gb interface

### ISSUE THREAD

**Issue by michaeljs1990** [tumblr/collins#545]
If you have a card with only a 40Gb interface on it this is false. This may be the correct thing to do but would anyone oppose to adding a "Has 40Gb interface" tag to assets?

**Comment by byxorna** [comment]
@michaeljs1990 I think we should support arbitrary (read: dynamic nic classifications). I think it would be sweet to auto-infer classification, and do some rounding to make things look right, so a nic reporting 999999kbps in LSHW is reported as a 10g nic, and perhaps even expose interface (ethernet/IB) as well. Thoughts?
I think this will be more extensible if instead of relying on booleans (has 10g/has 40g, which gets confusing when 40g is a superset of 10g for some requirements), we should rely on numerics (i.e. at least 10g capacity, at least 40g capacity)

**Comment by byxorna** [comment]
Ive opened #548 to address this. I thought it would have been more complicated, but this is only a small tweak to the show overview page.
